# =========================
# SUBJECTS BY MAJORS
# =========================

TOTAL_MAJOR_HOURS = 134
subjects_by_major = {

    "AI & DS": {
        "Statistics 1": 3,
        "Lab Statistics 1": 1,
        "Discrete Mathematics": 3,
        "Calculus 1": 3,
        "Introduction to Programming": 3,
        "Lab C++ 1": 1,
        "IT Fundamentals": 3,
        "OOP 1": 3,
        "Lab OOP1": 1,
        "Data Structures": 3,
        "Introduction to Datascience":3,
        "Probability & Statistics": 3,
        "Linear Algebra": 3,
        "Databases": 3,
        "Lab Data Base": 1,
        "Algorithms": 3,
        "OOP 2": 3,
        "Machine Learning": 3,
        "Artificial Intelligence": 3,
        "Data Mining": 3,
        "Big Data": 3,
        "Data Visualization": 3,
        "Operating Systems": 3,
        "Computer Networks": 3,
        "Deep Learning": 3,
        "NLP": 3,
        "Advanced AI": 3,
        "ML Applications": 3,
        "Graduation Project": 3
    },

    "CYS": {
        "Introduction to Programming": 3,
        "Lab C++": 1,
        "Discrete Mathematics": 3,
        "Calculus 1": 3,
        "Statistics 1": 3,
        "IT Fundamentals": 3,
        "OOP 1": 3,
        "Lab OOP 1": 1,
        "Data Structures": 3,
        "Databases": 3,
        "Lab Data Base": 1,
        "Computer Networks": 3,
        "Operating Systems": 3,
        "Algorithms": 3,
        "Cryptography": 3,
        "Cyber Security Fundamentals": 3,
        "Network Security": 3,
        "Ethical Hacking": 3,
        "Digital Forensics": 3,
        "Malware Analysis": 3,
        "Cloud Security": 3,
        "Penetration Testing": 3,
        "Intrusion Detection Systems": 3,
        "Graduation Project": 3
    },

    "CSD": {
        "Introduction to Programming": 3,
        "Lab C++ 1": 1,
        "Discrete Mathematics": 3,
        "Calculus 1": 3,
        "Statistics 1": 3,
        "IT Fundamentals": 3,
        "OOP 1": 3,
        "Lab OOP 1": 1,
        "Data Structures": 3,
        "Databases": 3,
        "Lab Data Base": 1,
        "Algorithms": 3,
        "OOP 2": 3,
        "Operating Systems": 3,
        "Computer Networks": 3,
        "Artificial Intelligence": 3,
        "IoT Fundamentals": 3,
        "Human Computer Interaction": 3,
        "Cloud Computing": 3,
        "Smart Devices Programming": 3,
        "IoT Applications": 3,
        "Cyber Security for IoT": 3,
        "Graduation Project": 3
    },

    "CIS": {
        "Introduction to Programming": 3,
        "Lab C++": 1,
        "Discrete Mathematics": 3,
        "Calculus 1": 3,
        "Statistics 1": 3,
        "IT Fundamentals": 3,
        "OOP 1": 3,
        "Lab OOP 1": 1,
        "Web Development 1": 3,
        "Data Structures": 3,
        "Web Development 2": 3,
        "Databases": 3,
        "Lab Data Base": 1,
        "Algorithms": 3,
        "OOP 2": 3,
        "Information Systems Analysis": 3,
        "Data Mining": 3,
        "Information Retrieval": 3,
        "Computer Networks": 3,
        "Software Engineering": 3,
        "IT Project Management": 3,
        "Database Administration": 3,
        "Graduation Project": 3
    }
}
