# =========================
# SUBJECTS BY MAJORS
# =========================

subjects_by_major = {

    "AI & DS": [
        "Statistics 1",
        "Lab Statistics 1",
        "Discrete Mathematics",
        "Calculus 1",
        "Introduction to Programming",
        "C++ 1",
        "IT Fundamentals",
        "OOP 1",
        "Lab OOP1",
        "Data Structures",
        "Probability & Statistics",
        "Linear Algebra",
        "Databases",
        "Lab Data Base",
        "Algorithms",
        "OOP 2",
        "Machine Learning",
        "Artificial Intelligence",
        "Data Mining",
        "Big Data",
        "Data Visualization",
        "Operating Systems",
        "Computer Networks",
        "Deep Learning",
        "NLP",
        "Advanced AI",
        "ML Applications",
        "Graduation Project"
    ],

    "CYS": [
        "Introduction to Programming",
        "Lab C++",
        "Discrete Mathematics",
        "Calculus 1",
        "Statistics 1",
        "IT Fundamentals",
        "OOP 1",
        "Lab OOP 1",
        "Data Structures",
        "Databases",
        "Lab Data Base",
        "Computer Networks",
        "Operating Systems",
        "Algorithms",
        "Cryptography",
        "Cyber Security Fundamentals",
        "Network Security",
        "Ethical Hacking",
        "Digital Forensics",
        "Malware Analysis",
        "Cloud Security",
        "Penetration Testing",
        "Intrusion Detection Systems",
        "Graduation Project"
    ],

    "CSD": [
        "Introduction to Programming",
        "Lab C++ 1",
        "Discrete Mathematics",
        "Calculus 1",
        "Statistics 1",
        "IT Fundamentals",
        "OOP 1",
        "Lab OOP 1",
        "Data Structures",
        "Databases",
        "Lab Data Base ",
        "Algorithms",
        "OOP 2",
        "Operating Systems",
        "Computer Networks",
        "Artificial Intelligence",
        "IoT Fundamentals",
        "Human Computer Interaction",
        "Cloud Computing",
        "Smart Devices Programming",
        "IoT Applications",
        "Cyber Security for IoT",
        "Graduation Project"
    ],

    "CIS": [
        "Introduction to Programming",
        "Lab C++",
        "Discrete Mathematics",
        "Calculus 1",
        "Statistics 1",
        "IT Fundamentals",
        "OOP 1",
        "Lab OOP1 ",
        "Web Development 1",
        "Data Structures",
        "Web Development 2",
        "Databases",
        "Lab Data Base ",
        "Algorithms",
        "OOP 2",
        "Information Systems Analysis",
        "Data Mining",
        "Information Retrieval",
        "Computer Networks",
        "Software Engineering",
        "IT Project Management",
        "Database Administration",
        "Graduation Project"
    ]
}